backend:
  name: github
  repo: develijahlee/yonseiuicscribe

media_folder: src/content/images
public_folder: ./images

collections:
  - name: blog
    label: Blog
    folder: src/content
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: author, label: author, widget: string }
      - { name: date, label: Date (YYYY-MM-DD), widget: string }
      - { name: category, label: Category (Capitalize first letter), widget: string }
      - { name: featuredImage, label: Featured Image File Name (change spaces into dashes), widget: string, default: ./images/ }
      - { name: body, label: Body, widget: markdown }