backend:
  name: github
  repo: develijahlee/yonseiuicscribe

media_folder: src/content/assets
public_folder: ./assets

collections:
  - name: blog
    label: Blog
    folder: src/content
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: date, label: Date, widget: string }
      - { name: author, label: author, widget: string }
      - { name: category, label: Category, widget: string }
      - { name: featuredImage, label: Featured Image, widget: string, default: ./assets/ }
      - { name: body, label: Body, widget: markdown }